### ISSUE TITLE
Feature Request - add active time schedule

### ISSUE THREAD

**Issue by keylogicjohan** [kirei/hass-chargeamps#19]
Hello

I'm using this component for load balancing, and it works great!
But I would love to see the feature to activate the time schedule and not youst disable or activate.

Thanks again for a great integration

**Comment by jschlyter** [comment]
I haven't even implemented support for schedules in https://github.com/kirei/python-chargeamps, because given that you have Home Assistant for automation I somehow assumed one doesn't need the built in schedules as well. What is use case? HA not online all the time or need for local control? Is the schedule implemented on the EVSE itself or is it in fact a cloud service offered by ChargeAmps?

**Comment by jschlyter** [comment]
Any updates on the use case?

**Comment by jschlyter** [comment]
No response, closing for now
